name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v1

    - name: tf init
      uses: "hashicorp/terraform-github-actions/init@v0.1.4"

    - name: tf verify
      uses: "hashicorp/terraform-github-actions/validate@v0.1.4"
